### ISSUE TITLE
Addition of options & head method (Feature Request)

### ISSUE THREAD

**Issue by mark-todd** [DaveLegg/dlpwd-router#1]
Hi there,

It would be useful if this router package supported the "options" method - don't mind making a PR for this if you like. Also, I believe put and patch need to be added to the private attrs list here: https://github.com/DaveLegg/dlpwd-router/blob/master/Router.php#L13

Many thanks,

Mark Todd

**Comment by mark-todd** [comment]
I've also found the head method would be useful, so I'm adding this to the scope of the PR

**Comment by DaveLegg** [comment]
Thanks Mark, I've merged your PR

**Comment by mark-todd** [comment]
Thanks Dave that's great! Just seen the new release
